/**
 * The handbooks reach the image — four files that must agree, on disk. No db,
 * no DOM, no Docker.
 *
 * `test/chalk.test.mjs`'s trick again, applied to the thing that broke a deploy.
 * A handbook is generated by `docs/handbook-src/build.mjs`, copied into
 * `dist/web` by `postbuild`, into the build stage by `app/Dockerfile`, and is
 * allowed into the build *context* by `.dockerignore` — which excludes `docs/*`
 * and names each document it lets back in.
 *
 * **Only one of those four can fail on a developer's machine.** `npm run build`
 * runs in a repo where every file is present, so it cannot notice that the
 * Dockerfile or the ignore file never heard of a new document. 0.10.4 shipped
 * with `build.mjs` and `postbuild` updated and the other two not; the image
 * build died on the server with `cp: can't stat`, which reads like a missing
 * file rather than an ignored one. HANDOFF §14d is the run.
 *
 * Every list here is read out of the file that owns it. Writing the document
 * names into this test would make it a fifth copy — and the one that goes stale
 * silently, because a test that agrees with itself always passes.
 */

import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const APP = join(import.meta.dirname, '..');
const ROOT = join(APP, '..');
const read = (...parts) => readFileSync(join(ROOT, ...parts), 'utf8');

/**
 * What `postbuild` copies out of `docs/`, as repo-relative paths.
 *
 * `postbuild` runs with `app/` as its working directory, so it names them
 * `../docs/x.html`; everything else in this file speaks from the repo root,
 * which is also what Docker's build context is rooted at.
 */
function copiedDocs() {
  const scripts = JSON.parse(read('app', 'package.json')).scripts;
  const matches = [...scripts.postbuild.matchAll(/\.\.\/(docs\/[\w.-]+)/g)].map((m) => m[1]);
  assert.ok(matches.length > 0, 'postbuild copies nothing out of docs/ — did it move?');
  return [...new Set(matches)];
}

test('packaging: every doc postbuild copies exists', () => {
  // The cheapest of the four and the only one `npm run build` would also catch,
  // but it is what makes the failures below readable: without it, a typo in
  // `postbuild` reports as "the Dockerfile does not copy docs/hanbuch.html".
  for (const doc of copiedDocs()) {
    assert.ok(existsSync(join(ROOT, doc)), `${doc}: copied by postbuild, absent from the repo`);
  }
});

test('packaging: every doc postbuild copies is COPYd in the Dockerfile', () => {
  const copied = read('app', 'Dockerfile')
    .split('\n')
    .filter((line) => line.startsWith('COPY '))
    .flatMap((line) => [...line.matchAll(/(?<![\w/])(docs\/[\w.-]+)/g)].map((m) => m[1]));

  for (const doc of copiedDocs()) {
    assert.ok(copied.includes(doc), `${doc}: postbuild copies it, app/Dockerfile does not COPY it`);
  }
});

test('packaging: every doc postbuild copies survives .dockerignore', () => {
  // The one that actually bit. `docs/*` excludes the directory and each `!`
  // line lets one document back in, so a document missing from this list is
  // absent from the build context entirely — and Docker reports *that* as a
  // missing file, one layer away from where the mistake is.
  const lines = read('.dockerignore')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'));

  assert.ok(lines.includes('docs/*'), '.dockerignore no longer excludes docs/* — re-read this test');

  for (const doc of copiedDocs()) {
    assert.ok(lines.includes(`!${doc}`), `${doc}: excluded by docs/* and never allowed back in`);
  }
});

test('packaging: every doc the generator writes is one postbuild ships', () => {
  // The fourth file. This direction only: a document generated and never
  // shipped is a `/handbuch-…` route that 404s, which is the failure the other
  // three exist to prevent, arriving from the other end.
  const written = [...read('docs', 'handbook-src', 'build.mjs')
    .matchAll(/out:\s*"([\w.-]+)"/g)].map((m) => `docs/${m[1]}`);
  assert.ok(written.length > 0, 'build.mjs writes nothing — did DOCUMENTS move?');

  const shipped = copiedDocs();
  for (const doc of written) {
    assert.ok(shipped.includes(doc), `${doc}: generated by build.mjs, not copied by postbuild`);
  }
});
